= Migration of Ansible Automation Platform from RPM 2.6 to operator 2.6. 

- Prior to initiating the migration, validate that the source environment is stable and operational, and perform a full backup of the application.

- After that go to the systems from where you will do `scp` the `migration_artifact.tar` and `migration_artifact.tar.sha256` to the new systems. Make sure to replace the `-P <port-number>` and hostname according to your *RHDP login*. 
+
[source,bash,role=execute]
----
scp -P 30866 migration_artifact.tar lab-user@ssh.ocpv06.rhdp.net:/home/lab-user
scp -P 30866 migration_artifact.tar.sha256 lab-user@ssh.ocpv06.rhdp.net:/home/lab-user
----

- Begin by scaling down the AAP deployment using idle_aap:
+ 
[source,bash,role=execute]
----
oc patch ansibleautomationplatform aap --type=merge -p '{"spec":{"idle_aap":true}}'
----
+
Wait for component pods to terminate. Only the 6 operator pods will remain running.

- Scale down the AAP Gateway Operator and Controller Operator:
+ 
[source,bash,role=execute]
----
oc scale --replicas=0 deployment aap-gateway-operator-controller-manager automation-controller-operator-controller-manager
----

- Scale up the idled Postgres StatefulSet:
+ 
[source,bash,role=execute]
----
oc scale --replicas=1 statefulset.apps/aap-postgres-15
----

- Create a temporary PVC with appropriate settings and sizing:
+ 
[source,bash,role=execute]
----
vim aap-temp-pvc.yaml
----
+ 
[source,bash,role=execute]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aap-temp-pvc
  namespace: aap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
----
+
[source,bash,role=execute]
----
oc create -f aap-temp-pvc.yaml
----

- Obtain existing postgres image to use for temporary deployment and `copy` the image name:
+ 
[source,bash,role=execute]
----
echo $(oc get pod/aap-postgres-15-0 -o jsonpath="{.spec.containers[].image}")
----

- Create temporary postgres deployment with mounted temporary pvc: aap-temp-postgres.yaml
+ 
[source,bash,role=execute]
----
vim aap-temp-postgres.yaml
----
+ 
[source,bash,role=execute]
----
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aap-temp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aap-temp-postgres
  template:
    metadata:
      labels:
        app: aap-temp-postgres
    spec:
      containers:
        - name: aap-temp-postgres
          image: <postgres image from previous step>
          command:
            - /bin/sh
            - '-c'
            - sleep infinity
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: aap-temp-pvc
              mountPath: /tmp/aap-temp-pvc
      volumes:
        - name: aap-temp-pvc
          persistentVolumeClaim:
            claimName: aap-temp-pvc
----

+ 
[source,bash,role=execute]
----
oc create -f aap-temp-postgres.yaml
----

- Copy export artifact to temporary postgres pod:
(obtain the pod name and set as an ENV variable)
+ 
[source,bash,role=execute]
----
export AAP_TEMP_POSTGRES=$(oc get pods --no-headers -o custom-columns="NAME:.metadata.name" | grep aap-temp-postgres)
----
+ 
[source,bash,role=execute]
----
echo $AAP_TEMP_POSTGRES
----

- Copy the Created artifact created from *Chapter 2* to this system: 
+ 
[source,bash,role=execute]
----
oc cp migration_artifact.tar $AAP_TEMP_POSTGRES:/tmp/aap-temp-pvc/
oc cp migration_artifact.tar.sha256 $AAP_TEMP_POSTGRES:/tmp/aap-temp-pvc/
----

- Restore databases to AAP postgres using temporary postgres: (obtain postgres passwords for all 3 databases and postgres admin password)
+ 
[source,bash,role=execute]
----
echo
for secret in aap-controller-postgres-configuration aap-hub-postgres-configuration aap-gateway-postgres-configuration
do
  echo $secret
  echo "PASSWORD: `oc get secrets $secret -o jsonpath="{.data['password']}" | base64 -d`"
  echo "USER: `oc get secrets $secret -o jsonpath="{.data['username']}" | base64 -d`"
  echo "DATABASE: `oc get secrets $secret -o jsonpath="{.data['database']}" | base64 -d`"
  echo
done && echo "POSTGRES ADMIN PASSWORD: `oc get secrets aap-gateway-postgres-configuration -o jsonpath="{.data['postgres_admin_password']}" | base64 -d`"
----

- Now `exec` into temporary postgres deployment and cd to the mounted pvc containing copied artifact) 
+ 
[source,bash,role=execute]
----
oc exec -it deployment.apps/aap-temp-postgres -- /bin/bash
----
+ 
[source,bash,role=execute]
----
cd /tmp/aap-temp-pvc && ls -l
----
+ 
[source,bash,role=execute]
----
sha256sum --check migration_artifact.tar.sha256 
----
+ 
[source,bash,role=execute]
----
tar xf migration_artifact.tar && cd migration_artifact && sha256sum --check sha256sum.txt
----

.. Drop the automationcontroller Database and Provide the `POSTGRES ADMIN PASSWORD` to perform the operation.
+ 
[source,bash,role=execute]
----
(drop controller db)
dropdb -h aap-postgres-15 automationcontroller (supply postres admin password)
----

+ 
[source,bash,role=execute]
----
psql -U postgres -h aap-postgres-15

(alter user temporarily with createdb role)
postgres=# ALTER USER automationcontroller CREATEDB;

postgres=\q
----

.. Create a new database called automationcontroller using autoamtion Controller passowrd from `aap-controller-postgres-configuration`.
+ 
[source,bash,role=execute]
----
createdb -h aap-postgres-15 -U automationcontroller automationcontroller
----

.. Revert temporary user permission
+ 
[source,bash,role=execute]
----
psql -U postgres -h aap-postgres-15

postgres=# ALTER USER automationcontroller NOCREATEDB;
postgres=# \q
----

.. Restoring the database form the migration_artifact directory from the container and please make sure the provide their repecitve database passowrd while resotring the database. 
+ 
[source,bash,role=execute]
----
(restore controller db)
pg_restore --clean --if-exists --no-owner -h aap-postgres-15 -U automationcontroller -d automationcontroller controller/automationcontroller.pgc

(restore hub db)
pg_restore --clean --if-exists --no-owner -h aap-postgres-15 -U automationhub -d automationhub hub/automationhub.pgc

(restore gateway db)
pg_restore --clean --if-exists --no-owner -h aap-postgres-15 -U gateway -d gateway gateway/automationgateway.pgc

(exit pod)
exit
----

- Replace db field encryption secrets:
+ 
[source,bash,role=execute]
----
oc set data secret/aap-controller-secret-key secret_key="<unencoded
controller_secret_key value from secrets.yml>"

oc set data secret/aap-db-fields-encryption-secret secret_key="<unencoded
gateway_secret_key value from secrets.yml>"

oc set data secret/aap-hub-db-fields-encryption database_fields.symmetric.key="
<unencoded hub_db_fields_encryption_key value from secrets.yml>"
---- 

- Clean up Temporary Postgres and PVC:
+ 
[source,bash,role=execute]
----
oc delete -f aap-temp-postgres.yaml
----
+ 
[source,bash,role=execute]
----
oc delete -f aap-temp-pvc.yaml
---- 

Scale the Gateway and Controller Operators back up and wait for the gateway operator reconciliation loop to complete (postgres statefulset will be set back to idle)
+ 
[source,bash,role=execute]
----
oc scale --replicas=1 deployment aap-gateway-operator-controller-manager automation-controller-operator-controller-manager
---- 

- Scale AAP back up using idle_aap
+ 
[source,bash,role=execute]
----
oc patch ansibleautomationplatform aap --type=merge -p '{"spec":{"idle_aap":false}}'
----

ansibleautomationplatform.aap.ansible.com/aap patched

-  Wait for aap-gateway pod to be running and clean up old service endpoints:
+ 
[source,bash]
----
(wait for pod to be running)
pod/aap-gateway-6c989b846c-47b9l 2/2 Running 0 45s
----

-  Run aap-gateway-manage to deprovision instances
(obtain controller pod) export AAP_CONTROLLER_POD=$(oc get pods --no-headers -o  custom-columns=":metadata.name"
| grep aap-controller-task)

+ 
[source,bash,role=execute]
----
echo $AAP_CONTROLLER_POD
aap-controller-task-759b6d9759-r59q9
(exec into controller pod)
----
+ 
[source,bash,role=execute]
----
oc exec -it $AAP_CONTROLLER_POD -- /bin/bash

awx-manage list_instances
----

+ 
[source,bash,role=execute]
----
[controlplane capacity=642 policy=100%]
aap-controller-task-759b6d9759-r59q9 capacity=642 node_type=control
version=4.6.15 heartbeat="2025-06-12 21:39:48"
node1.example.org capacity=0 node_type=hybrid version=4.6.13 heartbeat="2025-
05-30 17:22:11"

[default capacity=0 policy=100%]
node1.example.org capacity=0 node_type=hybrid version=4.6.13 heartbeat="2025-
05-30 17:22:11"
node2.example.org capacity=0 node_type=execution version=ansible-runner-2.4.1
heartbeat="2025-05-30 17:22:08"
Remove old nodes with awx-manage (leave only aap-controller-task):
awx-manage deprovision_instance --host=node1.example.org
awx-manage deprovision_instance --host=node2.example.org
---- 

-  Run curl command to repair hub filesystem data
+ 
[source,bash,role=execute]
----
curl -d '{\"verify_checksums\": true }' -X POST -k https://<aap
url>/api/galaxy/pulp/api/v3/repair/ -u <admin_user>:<restored_admin_password>
----