= Operator Deployment LAB

We will be using *Product Enablement AAP Operator Deployment lab* LAB for this deployment. Please be aware that setting up a operator lab will take about fifty minutes. Following that, you can proceed with the installation procedures:

The following video will provide the step-by-step guide for installing the Ansible Automation Platform 2.6 operator:

video::aap2.6_operator_install.mp4[align="left",width=800,height=500]


All the followed steps in the video are shared below:

. Log in to the Red Hat OpenShift Container Platform.
. Navigate to Operators OperatorHub.
. Search for *Ansible Automation Platform* and click *Install*.
. Select a *stable-2.6*.
. Select namespace as default which will be *aap*.
. Click *Install*.
. Go to *Installed Operators* and there you will see *Ansible Automation Platform* operator installed click on it. 

. Select project as *aap* if it's not aap. 


oc scale --replicas=0 deployment automation-hub-operator-controller-manager

. Then scroll to the option *Ansible Automation Platform* and click on *Create instance* which will deploy all the components of *aap*.

. Provide the *Name* = *aap* on which will be used to create the resources for that *AAP* like network routes,secrets. 

 Note: There are many other options that we can customize according to the requirement but in this we will be taking care of very basic deployment. 

. Click on *Create* it will deploy the resournces which will take around 20 minutes. 

. On openshift dashboard *Click on* Networking and then routes and click on the *ansible* route or the *Name* given in Step 10 above.

. On openshift dashboard go to *Workloads* and then *Secrets* and search for *admin* . Click on it and copy the *password*. 

. Provide the *Red Hat login ID* to get the subscription for attaching it to the AAP and *60-day subscription to Red Hat Ansible® Automation Platform* or *Red Hat Developer Subscription for Individuals* subscription can be used for this lab.  

. Submit it and run the *Project sync* of the *Demo project* to confirm that the job is getting executed.