= Making Target Environment Ready

- Go to the *bastion* host. using the RHDP login page creds.

video::aap2.6_container_install.mp4[align="left",width=800,height=500]

- You will do `scp` the `migration_artifact.tar` and `migration_artifact.tar.sha256` to the new systems. 
+
[source,bash,role=execute]
----
scp migration_artifact.tar container.lab:/home/lab-user/
scp migration_artifact.tar.sha256 container.lab:/home/lab-user/
----

- Install the required and useful utilities:
+
[source,bash,role=execute]
----
ssh container.lab 
----
+
[source,bash,role=execute]
----
sudo dnf install -y wget git-core rsync vim ansible-core
----
 
*Lets have the Containerized setup ready*

- Go to the https://access.redhat.com/downloads/content/480/ver=2.6/rhel---9/2.6/x86_64/product-software[Installer,window=_blank] link and Get the installer link for *Ansible Automation Platform 2.6 Containerized Setup Bundle*.
+
Note: Please follow above and the next step one after another in order to avoid the link expiration error, as the copied URL has an expiration time. Reload the website for the new link if you are having trouble downloading the package.

. Download the installer file to the VM: 
+ 
[source,bash,role=execute]
---- 
 wget -O aap.tar.gz "<paste-link-here taken from step 3>"
----

. Extract the *aap.tar.gz* file using the following command:
+ 
[source,bash,role=execute]
---- 
 tar -xvf aap.tar.gz
----

. Using the *cd* command, enter the extracted folder. Then, use the *vim* command, open the *inventory-growth* file and make the following changes, wherever they appear throughout the entire *inventory-growth* file:
+ 
[source,bash,role=execute]
---- 
 cd <extracted-folder-from-step-6>
 vim inventory-growth

aap.example.org -> container.lab

<set your own> → redhat

<set your own> ← This value can be customized as per your need but remember to use the same while doing the login after the deployment. 
----
+
Note: Please click this link to learn how to use https://www.geeksforgeeks.org/basic-vim-commands/[Vim basic operations,window=_blank] and also to remove any node under `[automationeda]`. 

. Once the inventory file is ready follow the below steps to do the installation:
+
[source,bash,role=execute]
----
ansible-playbook -i inventory-growth ansible.containerized_installer.install
----

. Use the user *admin* and the *password* set during the time of installation. In the above video I set it to *redhat*. 

 Note: Try to use stronger password while doing the enterprise deployment 

. Provide the *Red Hat login ID* to get the subscription for attaching it to the AAP and *60-day subscription to Red Hat Ansible® Automation Platform* or *Red Hat Developer Subscription for Individuals* subscription can be used for this lab.

. After *Login* run the *Project sync* for the *Demo project* to confirm the job is getting executed.
