= Making Target Environment Ready

Before start working on the Migration lets clean the installed Ansible Automation platform version of 2.4 from the infrastructure and for that simple run the below command from the *bastion* host: 

[source,bash,role=execute]
----
ansible-playbook /home/lab-user/patch.yml -i "controller.lab," -i "hub.lab," -i "database.lab,"
----

- After that go to the systems from where you will do `scp` the `migration_artifact.tar` and `migration_artifact.tar.sha256` to the new systems. 
+
[source,bash,role=execute]
----
adding later after testing
----

- Go to the *bastion* host. using the RHDP login page creds. 

- Extract the Artifact on the home folder for the user running the containerized containers.
+
[source]
----
$ cd ~
$ sha256sum --check migration_artifact.tar.sha256
$ tar xf migration_artifact.tar
$ cd migration_artifact
$ sha256sum --check sha256sum.txt
----

 Note: The __hub_database_fields comes from the hub_db_fields_encryption_key in your secret. Extra Variables file:

  $ ansible-playbook -i inventory ansible.containerized_installer.install -e @~/artifact/secrets.yml -e "__hub_database_fields='{{ hub_db_fields_encryption_key }}'"

*Lets have the Containerized setup ready*

- Go to the https://access.redhat.com/downloads/content/480/ver=2.6/rhel---9/2.6/x86_64/product-software[Installer,window=_blank] link and Get the installer link for *Ansible Automation Platform 2.6 Containerized Setup Bundle*.
+
Note: Please follow above and the next step one after another in order to avoid the link expiration error, as the copied URL has an expiration time. Reload the website for the new link if you are having trouble downloading the package.

. Download the installer file to the VM: 
+ 
[source,bash,role=execute]
---- 
 wget -O aap.tar.gz "<paste-link-here taken from step 3>"
----

. Extract the *aap.tar.gz* file using the following command:
+ 
[source,bash,role=execute]
---- 
 tar -xvf aap.tar.gz
----

. Using the *cd* command, enter the extracted folder. Then, use the *vim* command, open the *inventory-growth* file and make the following changes, wherever they appear throughout the entire *inventory-growth* file:
+ 
[source,bash,role=execute]
---- 
 cd <extracted-folder-from-step-6>
 vim inventory-growth

<set your own> → redhat

<set your own> ← This value can be customized as per your need but remember to use the same while doing the login after the deployment. 

and 

db.example.org → database.lab
----
+
Note: Please click this link to learn how to use https://www.geeksforgeeks.org/basic-vim-commands/[Vim basic operations,window=_blank].

. Now lets add the addition details of the hosts where it needs to either install or upgrade the components: 
+
[source,bash,role=execute]
----
[automationgateway]
gateway.lab  

[automationcontroller]
controller.lab

[automationcontroller:vars]
peers=execution_nodes

[execution_nodes]

[automationhub]
hub.lab

[automationedacontroller]
eda.lab

[database]
database.lab

[all:vars]
----

. Once the inventory file is ready follow the below steps to do the installation:
+
[source,bash,role=execute]
----
$ ansible-playbook -i inventory-growth ansible.containerized_installer.install
----

. Use the user *admin* and the *password* set during the time of installation. In the above video I set it to *redhat*. 

 Note: Try to use stronger password while doing the enterprise deployment 

. Provide the *Red Hat login ID* to get the subscription for attaching it to the AAP and *60-day subscription to Red Hat Ansible® Automation Platform* or *Red Hat Developer Subscription for Individuals* subscription can be used for this lab.

. After *Login* run the *Project sync* for the *Demo project* to confirm the job is getting executed.
