= Migration Artifact Collection LAB

The migration artifact is a complete bundle of all the components you need to successfully move your AAP deployment from an RPM-based installation to either container or Operator based Deployment. It should be organized as follows:

video::migration_artifact.mp4[align="left",width=800,height=500]


- Simply `ssh` the hostname from the *bastion* host and perform the activity on the `gateway` node.
+
[source,bash,role=execute]
----
ssh gateway.lab  
----

*Create Migration Artifact*

Artifact Structure

The below architecture we will be creating so that it can be further moved to the Environment either for the migration of Container or Operator based deployment. 

[source,bash]
----
/migration_artifact/
├── manifest.yml          # Metadata
├── secrets.yml           # Sensitive data
├── sha256sum.txt         # Checksums
├── controller/
│   ├── controller.pgc    # DB dump
│   └── custom_configs/   # Custom Python files
├── hub/
│   └── hub.pgc
└── gateway/
    └── gateway.pgc
----

[source,bash,role=execute]
----
mkdir -p migration_artifact/controller/custom_configs migration_artifact/hub migration_artifact/gateway && touch migration_artifact/manifest.yml migration_artifact/secrets.yml migration_artifact/sha256sum.txt
----

- Edit the manifest.yml file using the vi command. This file is for reference only; it shows the backup version we are collecting.
+
[source,bash,role=execute]
----
vi manifest.yml
----
+
[source,bash,role=execute]
----
aap_version: 2.6
platform: rpm
components:
  - name: controller
    version: 4.7.1
  - name: hub
    version: 4.11.0
  - name: gateway
    version: 2.6.0
----

- Edit `secrets.yml` file which will be containg the below information as this is different for every environment so create it accordingly. 
+
[source,bash,role=execute]
----
controller_pg_database: <redacted>
controller_secret_key: <from /etc/tower/SECRET_KEY>
gateway_pg_database: <redacted>
gateway_secret_key: <from /etc/ansible-automation-platform/gateway/SECRET_KEY>
hub_pg_database: <redacted>
hub_secret_key: <from /etc/pulp/settings.py>
hub_db_fields_encryption_key: <from /etc/pulp/certs/database_fields.symmetric.key>
----

Note: Encrypt this file before transfer.

- The below is the correct way to collect information and fill the information in the `secrets.yml` file: 

For each of the component groups, you need to get the connection settings from one node. To do this, you must first access the host and become the root user by running `sudo -i` before running each of the commands listed below.

.. Access the *hub node* and gather the secret key and add to the hub_secret_key value in secrets.yml file.
+
[source,bash,role=execute]
----
ssh hub.lab 
----
+
[source,bash,role=execute]
----
sudo grep '^SECRET_KEY' /etc/pulp/settings.py | awk -F'=' '{ print $2 }'
----

.. On the *hub node* gather the `database_fields.symmetric.key` value and add to the `hub_db_fields_encryption_key` value in `secrets.yml` file.
+
[source,bash,role=execute]
----
sudo cat /etc/pulp/certs/database_fields.symmetric.key
----

.. On the Hub node you can run the below command to get the database realted information which will be used later to take backup.
+
[source,bash,role=execute]
----
sudo  grep '^DATABASES' /etc/pulp/settings.py
----

.. Access the *gateway node* and gather the secret key and add to the gateway_secret_key value in `secrets.yml`.
file.
+
[source,bash,role=execute]
----
ssh gateway.lab  
----
+
[source,bash,role=execute]
----
sudo  cat /etc/ansible-automation-platform/gateway/SECRET_KEY
----

.. On the *gateway node* you can run the below command to get the database realted information which will be used later to take backup:
+
[source,bash,role=execute]
----
sudo  aap-gateway-manage print_settings | grep '^DATABASES'
----

.. Access the *controller node* from the *bastion* host and gather the secret key and add to the controller_secret_key value in `secrets.yml` file.
+
[source,bash,role=execute]
----
ssh controller.lab 
----
+
[source,bash,role=execute]
----
sudo  cat /etc/tower/SECRET_KEY
----

.. Access the *controller node* you can run the below command to get the database realted information which will be used later to take backup:
+
[source,bash,role=execute]
----
sudo awx-manage print_settings | grep '^DATABASES'
----

.. From the *migration_artifact* directory on the *gateway node* run the below commands to create the databases *backup*. and Make sure you are a `sudo user` and the database password is same as of previous chapter i.e. *redhat* for all databases. 
+
[source,bash,role=execute]
----
using the below format to create command: 
 pg_dump -h <pg_hostname> -U <component_pg_user> -d <component_pg_name> --clean --create -Fc -f <component>/<component>.pgc
----

... To create the backup of *Automation Controller* database. 
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U awx -d awx --clean --create -Fc -f controller/automationcontroller.pgc
----

... To create the backup of *Unified UI* database.
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U automationgateway -d automationgateway --clean --create -Fc -f gateway/automationgateway.pgc
----

... To create the backup of *Automation Hub* database.
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U automationhub -d automationhub --clean --create -Fc -f hub/automationhub.pgc
----

.. Now let's go to `gateway node` and perfom the activity.
+
[source,bash,role=execute]
----
ssh gateway.lab  
----

.. Package the Migration artifact and send it to the system. 
+
[source,bash,role=execute]
----
cd /home/lab-user/migration_artifact/
----
+
[source,bash,role=execute]
----
[ -f sha256sum.txt ] && rm -f sha256sum.txt; find . -type f -name "*.pgc" -exec sha256sum {} \; >> sha256sum.txt
----
+
[source,bash,role=execute]
----
cat sha256sum.txt
cd ..
----
+
[source,bash,role=execute]
----
tar cf migration_artifact.tar migration_artifact
sha256sum migration_artifact.tar > migration_artifact.tar.sha256
sha256sum --check migration_artifact.tar.sha256
tar tvf migration_artifact.tar
----

Download the `migration_artifact.tar` and `migration_artifact.tar.sha256` to your local machine or transfer to the target node with the scp command for that exit the gateway node:

[source,bash,role=execute]
----
[lab-user@gateway tmp]$ exit
----

.. Bring the content to the *bastion* system.
+
[source,bash,role=execute]
----
scp gateway.lab:/home/lab-user/migration_artifact.tar .
scp gateway.lab:/home/lab-user/migration_artifact.tar.sha256  .
----

.. Now to copy this to your local machine please use the *Login Command* and *password* from the RHDP page as the *port* and *bastion* hostname will be diffrent for your systems: 
+
[source,bash,role=execute]
----
scp -P 30911 lab-user@ssh.ocpv04.rhdp.net:/home/lab-user/migration_artifact.tar .
----
+
[source,bash,role=execute]
----
scp -P 30911 lab-user@ssh.ocpv04.rhdp.net:/home/lab-user/migration_artifact.tar.sha256 .
----

The lab work is now concluded. The resulting `migration_artifact.tar` and `migration_artifact.tar.sha256` files can now be used to perform the migration to a new deployment method. This includes migrating to either the Containerized Ansible Automation Platform or the Operator Ansible Automation Platform.
