= Migration Artifact Collection LAB

Create a complete backup of the source environment using the below command before proceeding forward. 

[source,bash,role=execute]
----
 ./setup.sh -b
----

The migration artifact is a complete bundle of all the components you need to successfully move your AAP deployment from an RPM-based installation to either container or Operator based Deployment. It should be organized as follows:

- Simply `ssh` the hostname from the *bastion* host and perform the activity on the `gateway` node.
+
[source,bash,role=execute]
----
ssh gateway.lab  
----

*Create Migration Artifact*

Artifact Structure

The below architecture we will be creating so that it can be further moved to the Environment either for the migration of Container or Operator based deployment. 

[source,bash]
----
/migration_artifact/
├── manifest.yml          # Metadata
├── secrets.yml           # Sensitive data
├── sha256sum.txt         # Checksums
├── controller/
│   ├── controller.pgc    # DB dump
│   └── custom_configs/   # Custom Python files
├── hub/
│   └── hub.pgc
└── gateway/
    └── gateway.pgc
----

[source,bash,role=execute]
----
mkdir -p migration_artifact/controller/custom_configs migration_artifact/hub migration_artifact/gateway && touch migration_artifact/manifest.yml migration_artifact/secrets.yml migration_artifact/sha256sum.txt
----

- Create `manifest.yml` using vi command:
+
[source,bash,role=execute]
----
vi manifest.yml
----
+
[source,bash,role=execute]
----
aap_version: 2.6
platform: rpm
components:
  - name: controller
    version: 4.7.1
  - name: hub
    version: 4.11.0
  - name: gateway
    version: 2.6.0
----

- Creating a `secrets.yml` which will be containg the below information as this is different for every environment so create it accordingly. 
+
[source,bash,role=execute]
----
controller_pg_database: <redacted>
controller_secret_key: <from /etc/tower/SECRET_KEY>
gateway_pg_database: <redacted>
gateway_secret_key: <from /etc/ansible-automation-platform/gateway/SECRET_KEY>
hub_pg_database: <redacted>
hub_secret_key: <from /etc/pulp/settings.py>
hub_db_fields_encryption_key: <from /etc/pulp/certs/database_fields.symmetric.key>
----

Note: Encrypt this file before transfer.

- The below is the correct way to collect information and fill the information in the `secrets.yml` file: 

For each of the component groups, you need to get the connection settings from one node. To do this, you must first access the host and become the root user by running `sudo -i` before running each of the commands listed below.

.. Access the *hub node* and gather the secret key and add to the hub_secret_key value in secrets.yml file.
+
[source,bash,role=execute]
----
ssh hub.lab 
----
+
[source,bash,role=execute]
----
grep '^SECRET_KEY' /etc/pulp/settings.py | awk -F'=' '{ print $2 }'
----

.. On the *hub node* gather the `database_fields.symmetric.key` value and add to the
`hub_db_fields_encryption_key` value in `secrets.yml` file.
+
[source,bash,role=execute]
----
cat /etc/pulp/certs/database_fields.symmetric.key
----

.. On the Hub node you can run the below command to get the database realted information which will be used later to take backup.
+
[source,bash,role=execute]
----
grep '^DATABASES' /etc/pulp/settings.py
----

.. Access the *gateway node* and gather the secret key and add to the gateway_secret_key value in secrets.yml
file.
+
[source,bash,role=execute]
----
ssh gateway.lab  
----
+
[source,bash,role=execute]
----
cat /etc/ansible-automation-platform/gateway/SECRET_KEY
----

.. On the *gateway node* you can run the below command to get the database realted information which will be used later to take backup:
+
[source,bash,role=execute]
----
aap-gateway-manage print_settings | grep '^DATABASES'
----

.. Access the *controller node* from the *bastion* host and gather the secret key and add to the controller_secret_key value in `secrets.yml` file.
+
[source,bash,role=execute]
----
ssh controller.lab 
----
+
[source,bash,role=execute]
----
cat /etc/tower/SECRET_KEY
----

.. Access the Controller node you can run the below command to get the database realted information which will be used later to take backup:
+
[source,bash,role=execute]
----
awx-manage print_settings | grep '^DATABASES'
----

.. From the *migration_artifact* directory on the *gateway node* run the below commands from *migration_artifact* directory to create *backup* the databases. and Make sure you are a `sudo user` and the database password in the previous chapter that we set was *redhat* for database. 
+
[source,bash,role=execute]
----
using the below format to create command: 
 pg_dump -h <pg_hostname> -U <component_pg_user> -d <component_pg_name> --clean --create -Fc -f <component>/<component>.pgc
----

... To create the backup of *Automation Controller* database. 
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U awx -d awx --clean --create -Fc -f controller/automationcontroller.pgc
----

... To create the backup of *Unified UI* database.
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U automationgateway -d automationgateway --clean --create -Fc -f gateway/automationgateway.pgc
----

... To create the backup of *Automation Hub* database.
+
[source,bash,role=execute]
----
pg_dump -h database.lab -U automationhub -d automationhub --clean --create -Fc -f hub/automationhub.pgc
----

.. Export Automation Controller custom configurations If any custom settings exists on the `/etc/tower/conf.d`,
copy them to `/tmp/backups/artifact/controller/custom_configs`.

. Configuration files on controller which are managed by the installer and not considered custom:
+
[source,bash,role=execute]
----
/etc/tower/conf.d/postgres.py
/etc/tower/conf.d/channels.py
/etc/tower/conf.d/caching.py
/etc/tower/conf.d/cluster_host_id.py
----

.. From the *bastion* take the ssh to the `controller.lab` node.
+
[source,bash,role=execute]
----
ssh controller.lab  
----

.. create a custom_config of the controller.
+
[source,bash,role=execute]
----
sudo -i
----
+
[source,bash,role=execute]
----
cd /etc/tower/conf.d
----
+
[source,bash,role=execute]
----
tar -rf custom_config.tar.gz execution_environments.py ha.py container_groups.py gateway.py insights.py subscription_usage_model.py
----
+
[source,bash,role=execute]
----
mv custom_config.tar.gz /home/lab-user/
chown lab-user /home/lab-user/custom_config.tar.gz
----
+
[source,bash,role=execute]
----
exit
----
+
[source,bash,role=execute]
----
exit
----

.. Now you are on the *bastion* node. 
+
[source,bash,role=execute]
----
scp controller.lab:/home/lab-user/custom_config.tar.gz .
----
+
[source,bash,role=execute]
----
scp custom_config.tar.gz gateway.lab:/home/lab-user/migration_artifact/controller/custom_configs/
----

.. Now let's go to `gateway node` and make the Controller custom config ready. 
+
[source,bash,role=execute]
----
ssh gateway.lab  
----
+
[source,bash,role=execute]
----
cd /home/lab-user/migration_artifact/controller/custom_configs
----
+
[source,bash,role=execute]
----
tar -xvf custom_config.tar.gz 
----
+
[source,bash,role=execute]
----
rm -rf custom_config.tar.gz
----

.. Package the Migration artifact and send it to the system. 
+
[source,bash,role=execute]
----
cd /home/lab-user/migration_artifact/
----
+
[source,bash,role=execute]
----
[ -f sha256sum.txt ] && rm -f sha256sum.txt; find . -type f -name "*.pgc" -exec sha256sum {} \; >> sha256sum.txt
----
+
[source,bash,role=execute]
----
cat sha256sum.txt
cd ..
----
+
[source,bash,role=execute]
----
tar cf migration_artifact.tar migration_artifact
sha256sum migration_artifact.tar > migration_artifact.tar.sha256
sha256sum --check migration_artifact.tar.sha256
tar tvf migration_artifact.tar
----

- Download the `migration_artifact.tar` and `migration_artifact.tar.sha256` to your local machine or transfer to the target node with the scp command for that exit the gateway node:
+
[source,bash,role=execute]
----
[lab-user@gateway tmp]$ exit
----

.. Bring the content to the *bastion* system.
+
[source,bash,role=execute]
----
scp gateway.lab:/tmp/migration_artifact.tar .
scp gateway.lab:/tmp/migration_artifact.tar.sha256  .
----
+
[source,bash,role=execute]
----
exit
----

... Now to copy this to your local machine please use the 
*Login Command* and *password* from the RHDP page as the port and *bastion* hostname will be diffrent for your systems: 
+
[source,bash,role=execute]
----
scp -P 30911 lab-user@ssh.ocpv04.rhdp.net:/home/lab-user/migration_artifact.tar .
----
+
[source,bash,role=execute]
----
scp -P 30911 lab-user@ssh.ocpv04.rhdp.net:/home/lab-user/migration_artifact.tar.sha256 .
----
+
[source,bash,role=execute]
----
ll migration*
----

Your lab work is done and now the files `migration_artifact.tar` and `migration_artifact.tar.sha256` can be used to migrate to any other deployment method either its *Cotainerized Ansible Automation platform* or *Operator Ansible Automation platform* . 

