= Fast-Track Ansible Automation Platform Migration

This training focuses only on migrating the main components of Ansible Automation Platform. You'll need to manually re-create or re-import the following items in your new environment:

- Event-Driven Ansible (EDA) configurations and content
- Instance group configurations
- Content from Automation Hub
- Custom Certificate Authority for the receptor mesh
- Any custom execution environments (the default one is included)

When we talk about migrating from an RPM to a container or operator-based installation, we're really talking about a major shift. The biggest difference is that we're moving the entire infrastructure from living directly on the system to being managed by container technology.

So this course is divided into multiple sections: 
- First we will talk about a simple upgrade from AAP 2.4 to AAP 2.6 `RPM` 
- Then we talk about migrating AAP 2.6 RPM tp AAP 2.6 `Containerized`. 
- Then we talk about migrating AAP 2.6 RPM tp AAP 2.6 `Operator`. 



## System List

The below systems will be used in the exercise for the initial 2 chapters.

[cols="1,2a", options="header"]
|===
|Number of Systems |Hostname
|System 1 |gateway.lab
|System 2 |controller.lab
|System 3 |hub.lab
|System 4 |eda.lab
|System 5 |database.lab
|===

