= Migration Artifact Collection LAB

The migration artifact is a complete bundle of all the components you need to successfully move your AAP deployment from an RPM-based installation to either container or . It should be organized as follows:

*Artifact checking*
 
Before starting with the migration please check if we have the correct postgress version 15 of the database using the below command: 

- You can verify your current PostgreSQL version by connecting to your database server and running the following command as the postgres user:

[source,bash,role=execute]
----

$ psql -c 'SELECT version();'

----
   

- You can verify the database sizes by connecting to your database server and running the following command as the postgres user and make sure that you have enough free storage space to create the backups: 

[source,bash,role=execute]
----
 $ psql -c '\l+'
----


*Create Migration Artifact*

- Artifact Structure
+
The below architecture we will be creating so that it can be further moved to the Environment either for the migration of Container or Operator based deployment. 

[source,bash,role=execute]
----
/migration_artifact/
├── manifest.yml          # Metadata
├── secrets.yml           # Sensitive data
├── sha256sum.txt         # Checksums
├── controller/
│   ├── controller.pgc    # DB dump
│   └── custom_configs/   # Custom Python files
├── hub/
│   └── hub.pgc
└── gateway/
    └── gateway.pgc
----

- Create manifest.yml
+
[source,bash,role=execute]
----
aap_version: 2.5
platform: rpm
components:
  - name: controller
    version: x.y.z
  - name: hub
    version: x.y.z
  - name: gateway
    version: x.y.z
----

- Create secrets.yml
+
[source,bash,role=execute]
----
controller_pg_database: <redacted>
controller_secret_key: <from /etc/tower/SECRET_KEY>
gateway_pg_database: <redacted>
gateway_secret_key: <from /etc/ansible-automation-platform/gateway/SECRET_KEY>
hub_pg_database: <redacted>
hub_secret_key: <from /etc/pulp/settings.py>
hub_db_fields_encryption_key: <from /etc/pulp/certs/database_fields.symmetric.key>
----

Security Note: Encrypt this file before transfer.


- Create a complete backup of the source environment using the below command. 

- /setup.sh -e 'backup_dest=/path/to/backup_dir/' -b

- Create some data: 

For each of the component groups, you need to get the connection settings from one node. To do this, you must first access the host and become the root user before running each of the commands listed below.


.. Access the Controller node and run:
+
[source,bash,role=execute]
----
# awx-manage print_settings | grep '^DATABASES'
----

.. Access the Hub node and run:
+
[source,bash,role=execute]
----
# grep '^DATABASES' /etc/pulp/settings.py
----

.. Access the Gateway node and run:
+
[source,bash,role=execute]
----
# aap-gateway-manage print_settings | grep '^DATABASES'
# mkdir -p /tmp/backups/artifact/{controller,gateway,hub}
# mkdir -p /tmp/backups/artifact/controller/custom_configs
# touch /tmp/backups/artifact/secrets.yml
# cd /tmp/backups/artifact/
----

.. Access the controller node and gather the secret key and add to the controller_secret_key value in
secrets.yml file.
+
[source,bash,role=execute]
----
# cat /etc/tower/SECRET_KEY
----

.. Access the hub node and gather the secret key and add to the hub_secret_key value in secrets.yml file.
+
[source,bash,role=execute]
----
# grep '^SECRET_KEY' /etc/pulp/settings.py | awk -F'=' '{ print $2 }'
----

.. Access the hub node and gather the database_fields.symmetric.key value and add to the
hub_db_fields_encryption_key value in secrets.yml file.
+
[source,bash,role=execute]
----
# cat /etc/pulp/certs/database_fields.symmetric.key
----

.. Access the gateway node and gather the secret key and add to the gateway_secret_key value in secrets.yml
file.
+
[source,bash,role=execute]
----
# cat /etc/ansible-automation-platform/gateway/SECRET_KEY
----

.. Export Automation Controller custom configurations If any custom settings exists on the `/etc/tower/conf.d`,
copy them to `/tmp/backups/artifact/controller/custom_configs`.

.. Configuration files on controller which are managed by the installer and not considered custom:
+
[source,bash,role=execute]
----
/etc/tower/conf.d/postgres.py
/etc/tower/conf.d/channels.py
/etc/tower/conf.d/caching.py
/etc/tower/conf.d/cluster_host_id.py
----

Package the artifact
[source,bash,role=execute]
----
# cd /tmp/backups/artifact/
# [ -f sha256sum.txt ] && rm -f sha256sum.txt; find . -type f -name "*.pgc" -exec
sha256sum {} \; >> sha256sum.txt
# cat sha256sum.txt
# cd ..
# tar cf artifact.tar artifact
# sha256sum artifact.tar > artifact.tar.sha256
# sha256sum --check artifact.tar.sha256
# tar tvf artifact.tar
----

- Download the artifact.tar and artifact.tar.sha256 to your local machine or transfer to the target
node with the scp command.
